name: conditional workflow
on:
  pull_request:
    types: [opened, reopened]
jobs:
  print_pr_size_large:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.additions >= 10 }}
    steps:
      - run: echo 'ðŸ¤¯ This PR is large!'
      - run: echo '${{ github.event.pull_request.additions }}'
  print_pr_size_small:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.additions < 10 }}
    steps:
      - run: echo 'This is a baby PR ðŸ£'
      - run: echo '${{ github.event.pull_request.additions }}'
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: friendsofgo/pr-size-labeler@v1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: "10"
          s_max_size: "100"
          m_max_size: "500"
          l_max_size: "1000"
          fail_if_xl: "false"
          message_if_xl: "This PR is so big! Please, split it ðŸ˜Š"
