name: Print GitHub Environment Variables
on: [push]
jobs:
  print_github_env_vars:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'â˜„ï¸ Event Context ${{ github.event }}'
      - run: echo 'ğŸ‰ Triggered by a ${{ github.event_name }} event.'
      - run: echo 'ğŸ§ Running on a ${{ runner.os }} server hosted by GitHub!'
      - run: echo 'ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.'
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  print_context_env_vars:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'ğŸ„ Runner context ${{ toJSON(github) }}'
      - run: echo 'ğŸŒ¼ Job context ${{ toJSON(job) }}'
      - run: echo 'ğŸ’ Steps context ${{ toJSON(steps) }}'
      - run: echo 'ğŸŒ¦ Runner context ${{ toJSON(runner) }}'
      - run: echo 'ğŸ Strategy context ${{ toJSON(strategy) }}'
      - run: echo 'ğŸ¦‹ Matrix context ${{ toJSON(matrix) }}'
